### ISSUE TITLE
go program exists

### ISSUE THREAD

**Issue by sureshsankaran** [pojntfx/go-app-grpc-chat-frontend-web#1]
Really appreciate sharing wasm/websocket example. Pls check below snapshot where i see wasm program exiting. Could you pls fix this ?

![Screen Shot 2020-09-14 at 12 36 04 PM](https://user-images.githubusercontent.com/7672865/93130091-dfdbdc80-f686-11ea-92c3-ae2edfb20d7a.png)

**Comment by pojntfx** [comment]
@sureshsankaran Thanks for the bug report! Fixed from 3b6f3466155e4f148f9bc55446810bb50cc7fb13 upwards; I added automatic reconnection support. Don't forget to also pull the latest changes from https://github.com/pojntfx/go-app-grpc-chat-backend as well however, the API has changed (it now supports gRPC bi-directional streaming and doesn't drop messages when clients reconnect).

**Comment by sureshsankaran** [comment]
still getting an error. Am i missing something. As per readme, all we need to do is 
* git clone 
* make 
* make run

correct ?

![Screen Shot 2020-09-14 at 5 03 17 PM](https://user-images.githubusercontent.com/7672865/93149816-314a9280-f6ac-11ea-98ac-654b010a4d10.png)

**Comment by pojntfx** [comment]
I think the caches might be an issue and thus the new WASM binary isn't being loaded; go-app requires you to clear them when reloading. If you're on macOS, try refreshing with `CMD - SHIFT - R` instead of `CMD - R`; that should reload the app and use the newer version. And also, your way of `clone - make - make run` should be working ;)

**Comment by pojntfx** [comment]
Closing due to lack of response of reporter and positive local test.
